backend-design-pattern/BackEnd.WEBUI/Models/CategoryListViewModel.cs
using BackEnd.Entities.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BackEnd.WEBUI.Models
{
    public class CategoryListViewModel
    {
        public List<Category> Categories { get; set; }
        public int CurrentCategory { get; set; }
    }
}

backend-design-pattern/BackEnd.WEBUI/Models/ProductListViewModel.cs
using BackEnd.Entities.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BackEnd.WEBUI.Models
{
    public class ProductListViewModel
    {
        public List<Product> Products { get; set; }
        public PageInfo PageInfo { get; set; }
    }

    public class PageInfo
    {
        public int TotalItems { get; set; }
        public int PageCount { get; set; }
        public int CurrentCategory { get; set; }
        public int CurrentPage { get; set; }
        public int PageSize { get; set; }
        public int ItemsPerPage { get; set; }
        public int TotalPages()
        {
            return (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage);
        }
    }


}

backend-design-pattern/BackEnd.WEBUI/Components/CategoryListViewComponent.cs
using BackEnd.Business.Abstract;
using BackEnd.WEBUI.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BackEnd.WEBUI.Components
{
    public class CategoryListViewComponent:ViewComponent
    {
        ICategoryService _categoryService;

        public CategoryListViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public ViewViewComponentResult Invoke()
        {
            var model = new CategoryListViewModel
            {
                Categories = _categoryService.GetAll(),
                CurrentCategory = Convert.ToInt32(HttpContext.Request.Query["category"])
                
            };

            return View(model);
        }
    }
}

backend-design-pattern/BackEnd.WEBUI/Controllers/CartController.cs
using BackEnd.Business.Abstract;
using BackEnd.WEBUI.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BackEnd.WEBUI.Controllers
{
    public class CartController : Controller
    {
        private ICartSessionService _cartSessionService;
        private ICartService _cartService;
        private IProductService _productService;
        public CartController(ICartSessionService cartSessionService, ICartService cartService, IProductService productService)
        {
            _cartService = cartService;
            _cartSessionService = cartSessionService;
            _productService = productService;
        }
        public IActionResult AddToCart(int productId)
        {
            var productToBeAdded = _productService.GetById(productId);
            var cart = _cartSessionService.GetCart();

            _cartService.AddToCart(cart, productToBeAdded);
            _cartSessionService.SetCart(cart);

            TempData.Add("Message", string.Format("Ürününüz Eklendi."));

            return RedirectToAction("List", "Product");
        }
    }
}

backend-design-pattern/BackEnd.WEBUI/Controllers/ProductController.cs
using BackEnd.Business.Abstract;
using BackEnd.WEBUI.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BackEnd.WEBUI.Controllers
{
    public class ProductController:Controller
    {
        private IProductService _productService;
        public ProductController(IProductService productService)
        {
            _productService = productService;
        }

        public IActionResult Index(int category, int page = 1)
        {
            int pageSize = 5;
            var totalProduct = _productService.GetAll();
            var totalItems = totalProduct.Count();

            var productViewModel = new ProductListViewModel()
            {
                PageInfo = new PageInfo()
                {
                    TotalItems = totalItems,
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    CurrentCategory = category
                },

                Products = _productService.GetAll()
            };

            return View(productViewModel);
        }

    }
}

backend-design-pattern/BackEnd.WEBUI/Views/Product/Index.cshtml
@model BackEnd.WEBUI.Models.ProductListViewModel

@{ 
    Layout = "~/Views/_Layout.cshtml";
}
    <div>
        <table class="table table-responsive">
            <tr>
                <td>Ürün Adı</td>
                <td>Birim Fiyatı</td>
                <td>Stok Adeti</td>
                <td></td>
            </tr>

            @foreach (var product in Model.Products)
            {
                <tr>
                    <td>@product.ProductName</td>
                    <td>@product.UnitPrice</td>
                    <td>@product.UnitsInStock</td>
                    <td><a class="btn btn-sm btn-success" asp-controller="Cart" asp-action="AddToCart" asp-route-productId="@product.ProductId">Add To Cart</a></td>
                </tr>
            }

        </table>
    </div>

    <div class="row my-3">
        <div class="col">
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Önceki</a>
                    </li>


                    @for (int i = 0; i < Model.PageInfo.TotalPages(); i++)
                    {

                            <li class="page-item @(Model.PageInfo.CurrentPage==i+1?"active":"")">
                                <a class="page-link"
                                   href="/product/index?page=@(i + 1)">@(i + 1)</a>
                            </li>
                    }



                    <li class="page-item">
                        <a class="page-link" href="#">Sonraki</a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>

backend-design-pattern/BackEnd.WEBUI/Views/Shared/Components/CategoryList/Default.cshtml
@model BackEnd.WEBUI.Models.CategoryListViewModel

<div class="list-group">
    @foreach (var category in Model.Categories)
    {
        var css = "list-group-item";
        if (category.CategoryId == Model.CurrentCategory)
        {
            css += " active";
        }

        <a href="/product/index?category=@category.CategoryId" class="@css" >@category.CategoryName</a>
    }
</div>

backend-design-pattern/BackEnd.WEBUI/Views/Shared/_Navbar.cshtml
<div class="col-md-12">
    <header class="p-3 bg-dark text-white">
        <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                </a>

                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                    <li><a href="#" class="nav-link px-2 text-secondary">Anasayfa</a></li>
                    <li><a href="#" class="nav-link px-2 text-white">Ürünler</a></li>
                    <li><a href="#" class="nav-link px-2 text-white">Kategoriler</a></li>
                    <li><a href="#" class="nav-link px-2 text-white">Ödeme Yöntemleri</a></li>
                    <li><a href="#" class="nav-link px-2 text-white">Hakkında</a></li>
                </ul>

                <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
                    <input type="search" class="form-control form-control-dark" placeholder="Ara..." aria-label="Search">
                </form>

                <div class="text-end">
                    <button type="button" class="btn btn-outline-light me-2">Giriş Yap</button>
                    <button type="button" class="btn btn-warning">Kayıt Ol</button>
                </div>
            </div>
        </div>
    </header>
  </div>

backend-design-pattern/BackEnd.WEBUI/Views/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="../node_modules/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />

    <script src="../node_modules/bootstrap/dist/js/bootstrap.js"></script>
    <script src="../node_modules/jquery/dist/jquery.min.js"></script>

</head>
<body>

    <div>
        @await Html.PartialAsync("_Navbar")
    </div>

    <div class="container">
        <div class="row">
            <div class="col-md-3 my-3">
                @await Component.InvokeAsync("CategoryList")
            </div>

            <div class="col-md-9 my-2">
                @if (TempData["Message"] != null)
                {
                    <div class="alert alert-info" role="alert">@TempData["Message"]</div>
                }
                @RenderBody()
            </div>
        </div>
    </div>


</body>
</html>